title: Xiaojun Ren's Blog
description: happy coding
disqus_shortname: nicholasrensblog
url: https://nicholas.ren
baseurl: ""
remote_theme: sighingnow/jekyll-gitbook

# Plugins
plugins:
  - jekyll-paginate

# Default layouts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "modern-post"
      comments: true
      share: true

# Modern features
modern:
  reading_time: true
  social_sharing: true
  related_posts: true

owner:
  name: Xiaojun Ren
  avatar: avatar.png
  email: nicholas.x.ren@gmail.com
  twitter: '@nicholasren'
  github: nicholasren

timezone:      Australia/Melbourne
future:        true
highlighter:   rouge
markdown:      kramdown

# Pagination settings
paginate: 20
paginate_path: "/page/:num/"

destination: public
exclude:
- Rakefile
- Gemfile
- Gemfile.lock
- README.textile
- public
- config.rb
- wordpress.2011-02-22.xml
- import.rb
- config.ru
- vendor
- tmp
