title: Nicholas Ren's Blog
description: happy coding
disqus_shortname: nicholasrensblog
url: http://nicholasren.github.io

owner:
  name: Nicholas Ren
  avatar: avatar.jpg
  email: nicholas85211@gmail.com
  twitter: '@nicholasren'
  github: nicholasren

timezone:    China/Beijing
future:      true
pygments:    true
markdown:    rdiscount
paginate:    5

destination: public
exclude:
- Rakefile
- Gemfile
- Gemfile.lock
- README.textile
- public
- config.rb
- wordpress.2011-02-22.xml
- import.rb
- config.ru
- tmp
