title: Nicholas Ren's Blog
description: happy coding
disqus_shortname: nicholasrensblog
#url: http://nicholas.ren
google_analytics: 'UA-26893631-1'

owner:
  name: Nicholas Ren
  avatar: avatar.png
  email: nicholas.x.ren@gmail.com
  twitter: '@nicholasren'
  github: nicholasren

timezone:      Australia/Melbourne
future:        true
highlighter:   pygments
markdown:      kramdown
paginate:     5

destination: public
exclude:
- Rakefile
- Gemfile
- Gemfile.lock
- README.textile
- public
- config.rb
- wordpress.2011-02-22.xml
- import.rb
- config.ru
- vendor
- tmp
